defaultDevice = 1
# The device # to connect to by default.
# Set to 0 to ask every time.


[targets.1]
name = "localhost"
ip = "127.0.0.1"
port = 9000
#Connect to this computer.
# You probably don't need to change this

[targets.2]
name = "Quest 2"
ip = "192.168.0.43"
port = 9000
# Fill in name and ip with the name and IP of your receiving device.